config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  root :to => "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings"
    get "followers" => "relationships#followers"
  end
  
  get "searches" => "searches#search"
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  def create
    relationship = Relationship.new(follower_id: current_user.id, followed_id: params[:user_id])
    relationship.save
    redirect_to request.referer
  end
  
  def destroy
    relationship = Relationship.find_by(follower_id: current_user.id, followed_id: params[:user_id])
    relationship.destroy
    redirect_to request.referer
  end
  
  def followings
    @users = User.find(params[:user_id]).followings
  end
  
  
  def followers
    @users = User.find(params[:user_id]).followers
  end
  
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if user.followed_by?(current_user) %>
  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: 'btn btn-info' %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: 'btn btn-success' %>
<% end %>

app/views/relationships/followers.html.erb
 <h2>Follower Users</h2>
 <%= render 'users/index', users: @users %>
 

app/views/relationships/followings.html.erb
 <h2>Follow Users</h2>
 <%= render 'users/index', users: @users %>
 