config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  root :to => "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings"
    get "followers" => "relationships#followers"
  end
  
  get "searches" => "searches#search"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  # userとrelationshipsが1:Nの関係
  has_many :relationships, class_name: "Relationship",
                           foreign_key: "follower_id",
                           dependent: :destroy
  
  # userとreverse_relationshipsが1:Nの関係
  has_many :reverse_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  
  # user->relationshipsテーブルを経由してfollowed(user)テーブル参照
  has_many :followings, through: :relationships, source: :followed
  
  # user->reverse_relationshipsテーブルを経由してfollower(user)テーブル参照
  has_many :followers, through: :reverse_relationships, source: :follower
  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true

  validates :introduction, length: { maximum: 50 }
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def followed_by?(user)
    followers.exists?(id: user.id)
  end
  
  def self.search_for(keyword, search)
    
    #検索カラム
    column = "name"
    
    # 完全一致検索
    if search == "perfect_match"
      User.where("#{column}": keyword)
    # 前方一致検索
    elsif search == "forward_match"
      User.where("#{column} LIKE ?", "#{keyword}%")
    # 後方一致検索
    elsif search == "backward_match"
      User.where("#{column} LIKE ?", "%#{keyword}")
    # 部分一致検索
    elsif search == "partial_match"
      User.where("#{column} LIKE ?", "%#{keyword}%")
    # それ以外
    else
      User.none
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<% if users.exists? %>
  <table class='table'>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th>follows</th>
        <th>followers</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td>
            <%= image_tag user.get_profile_image, size: '50x50' %>
          </td>
          <td>
            <%= user.name %>
          </td>
          <td>
            フォロー数:<%= user.followings.count %>
          </td>
          <td>
            フォロワー数:<%= user.followers.count %>
          </td>
          <td>
            <%# 一覧表示対象ユーザとログインユーザが一致する行はフォロー/フォロー解除ボタン非表示  %>
            <% if user != current_user %>
              <%= render 'relationships/btn', user: user %>
            <% end %>
          </td>
          <td>
            <%= link_to 'Show', user %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>ユーザは存在しません</p>
<% end %>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
</table>

<%# 一覧表示対象ユーザとログインユーザが一致する行はフォロー/フォロー解除ボタン非表示  %>
<% if user != current_user %>
  <%= render 'relationships/btn', user: user %>
<% else %>
  <div class='row'>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local: true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
    <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>