config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  root :to => "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings"
    get "followers" => "relationships#followers"
  end
  
  get "searches" => "searches#search"
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def search
    @keyword = params[:keyword]
    target = params[:target]
    search = params[:search]
    obj = Object.const_get(target)
    
    if @keyword.present?
      if target == "User"
        @results = User.search_for(@keyword, search)
      elsif target == "Book"
        @results = Book.search_for(@keyword, search)
      else
        redirect_to request.referer
      end
    else
      @results = obj.none
    end
    
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <div class="container">
  <div class="row justify-content-center my-3">
    <%= form_with url: searches_path, local: true, method: :get do |f| %>
      <%= f.text_field :keyword %>
      <%= f.select :target, {"User": "User", "Book": "Book"} %>
      <%= f.select :search, {"完全一致": "perfect_match", "前方一致": "forward_match", "後方一致": "backward_match", "部分一致": "partial_match"} %>
      <%= f.submit '検索' %>
    <% end %>
  </div>
  </div>
<% end %>

app/views/searches/search.html.erb
<% if @results.nil? %>
  <p>検索対象は存在しません</p>
<% else%>
  <% if @results.name == "User" %>
    <h2>Users search for "<%= @keyword %>"</h2>
    <%= render 'users/index', users: @results %>
  <% elsif @results.name == "Book" %>
    <h2>Books search for "<%= @keyword %>"</h2>
    <%= render 'books/index', books: @results %>
  <% else %>
    <p>検索対象は存在しません</p>
  <% end %>
<% end %>